### PR TITLE
Update distributed workloads wg

### PR DESCRIPTION
**Pull request by anishasthana**
cc @taneem-ibrahim @heyselbi @LaVLaS 

I have one additional question... With the introduction of https://github.com/opendatahub-io/odh-manifests/pull/789, could we make the case that the scope for this WG has been met?

### CODE REVIEW

**Review by taneem-ibrahim — APPROVED** [review]
/lgtm

**Comment by anishasthana** [comment]
@LaVLaS fyi

**Review by LaVLaS — APPROVED** [review]

**Comment by anishasthana** [comment]
image
Why is the PR blocked?

**Pull request merged**
