### PR TITLE
KServe Model Serving Runtime proposal (Single model deployment)

### PR DESCRIPTION
**Pull request by danielezonca**
Proposal for bringing the KServe Model Serving Runtime open source project into ODH.
See https://github.com/opendatahub-io/opendatahub-community/issues/54 for more details

I have also updated ModelMesh proposal to explain/link how the two components correlate

### CODE REVIEW

**Comment by danielezonca** [comment]
@Jooho @Xaenalt @retocode @skonto 
Do you have any comment about this proposal? 

@LaVLaS @taneem-ibrahim 
Can you please review/approve? 

I would like to proceed and merge into ODH

**Comment by LaVLaS** [comment]
Merging since the kserve changes are already merged into odh-manifests

**Review by ReToCode — APPROVED** [review]
LGTM

**Comment by taneem-ibrahim** [comment]
LGTM

**Pull request merged**
