### PR TITLE
Iter8 proposal

### PR DESCRIPTION
**Pull request by sriumcp**
Proposal for bringing the Iter8 open source project into ODH. Please see #52

### CODE REVIEW

**Comment by sriumcp** [comment]
@anishasthana Absolutely. I requested access to the MLOps sig meeting docs.

My understanding based on conversations with @taneem-ibrahim is that we are presenting/demoing today 12PM Eastern... ?

**Comment by anishasthana** [comment]
Ah, yeah I see it's on the agenda for today. Perfect!

**Review by anishasthana — COMMENTED** [review]
I think this is worth bringing in for further proving out in the ODH. My comments from the SIG meeting have also been addressed. /lgtm

**Review by gmfrasca — COMMENTED** [review]
Looks good to me as well. Leaving review open for an ODH community maintainer to have final comments and/or approvals but barring that should be good to go.

/lgtm

**Comment by taneem-ibrahim** [comment]
Thank you for the iter8 proposal.

/lgtm

**Comment by anishasthana** [comment]
@LaVLaS fyi

**Pull request merged**
