### PR TITLE
Updated testing section

### PR DESCRIPTION
**Pull request by oshritf**

### CODE REVIEW

**Comment by oshritf** [comment]
reviewer @crobby

**Comment by nakfour** [comment]
@oshritf there is an error in your example notebook, 
``` spark_conf=SparkConf()```
This was not included and notebook was complaining spark_conf does not exist. After adding this I was able to import xskipper. However, I dont have the data that is supposed to be in 
```md_base_location = "/opt/app-root/src/example-metadata"```
Is it possible to provide a much simpler example so we can see this working.

**Comment by oshritf** [comment]
@nakfour md_base_location specifies where xskipper writes the metadata to and is populated in the notebook itself in Indexing a dataset  section later on, do you get an exception?

**Comment by nakfour** [comment]
@oshritf this works for me now, thank you

**Comment by oshritf** [comment]
@nakfour Could you add relevant reviewers for merging? tx!

**Comment by LaVLaS** [comment]
Closing this due to age

**Pull request closed without merging**
